openapi: 3.0.0
info:
  title: Reserveat API
  version: 1.0.0
  description: API for reserving tables in the restaurants using Reserveat
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server
paths:
  /restaurants:
    post:
      tags:
        - Restaurant
      summary: Create a new restaurant
      operationId: createRestaurant
      requestBody:
        description: Restaurant details
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/RestaurantInput.yaml'
      responses:
        '201':
          description: Restaurant created successfully
          content:
            application/json:
              schema:
                $ref: './components/schemas/RestaurantOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
  /restaurants/{restaurantId}:
    get:
      tags:
        - Restaurant
      summary: Get a restaurant by ID
      description: Returns a restaurant by ID
      parameters:
        - name: restaurantId
          in: path
          description: ID of the restaurant to retrieve
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Restaurant retrieved successfully
          content:
            application/json:
              schema:
                $ref: './components/responses/NotFound.yaml'
        '401':
          $ref: './components/responses/NotFound.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    put:
      summary: Edit a restaurant
      description: Update information for an existing restaurant.
      tags:
        - Restaurant
      parameters:
        - name: restaurantId
          in: path
          description: ID of the restaurant to update
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/RestaurantInput.yaml'
      responses:
        '200':
          description: Restaurant updated successfully
          content:
            application/json:
              schema:
                $ref: './components/schemas/RestaurantOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    delete:
      tags:
        - Restaurant
      summary: Delete a restaurant
      description: Deletes a restaurant and all its locations
      parameters:
        - name: restaurantId
          in: path
          description: ID of the restaurant to delete
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: Restaurant deleted successfully
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /restaurants/{restaurantId}/locations:
    post:
      summary: Create a new location to a restaurant
      tags:
        - Location
      parameters:
        - in: path
          name: restaurantId
          description: ID of the restaurant to which the location will be added
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/LocationInput.yaml'
      responses:
        '201':
          description: Location created successfully
          content:
            application/json:
              schema:
                $ref: './components/schemas/LocationOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /locations/{locationId}:
    get:
      summary: Get location details by ID
      tags:
        - Location
      parameters:
        - in: path
          name: locationId
          description: ID of the location to get
          required: true
          schema:
            type: integer
          example: 456
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components/schemas/LocationOutput.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    put:
      summary: Update location details by ID
      tags:
        - Location
      parameters:
        - in: path
          name: locationId
          description: ID of the location to update
          required: true
          schema:
            type: integer
          example: 456
        - in: header
          name: Authorization
          description: Access token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/LocationInput.yaml'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components/schemas/LocationOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    delete:
      summary: Delete a location for a restaurant
      tags:
        - Location
      parameters:
        - in: path
          name: locationId
          description: ID of the location to delete
          required: true
          schema:
            type: integer
          example: 456
      responses:
        '204':
          description: Location deleted successfully
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /locations/{locationId}/photos:
    post:
      tags:
        - Location
      summary: Add a photo to a location
      description: Add a photo to a location in a restaurant
      parameters:
        - in: path
          name: locationId
          description: ID of the location
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                description:
                  type: string
                  description: A short description of the photo
              required:
                - file
      responses:
        '200':
          description: Successfully added photo to the location
          content:
            application/json:
              schema:
                $ref: './components/schemas/PhotoOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    get:
      tags:
        - Location
      summary: Get all photos for a location.
      parameters:
        - in: path
          name: locationId
          required: true
          description: ID of the location.
          schema:
            type: integer
        - in: query
          name: limit
          required: false
          description: The maximum number of photos to return.
          schema:
            type: integer
      responses:
        '200':
          description: List of photos for the location.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/PhotoOutput.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
  /locations/nearby:
    get:
      tags:
        - Location
      summary: Get nearby locations
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitude of the user's location
          schema:
            type: number
            format: float
            example: 37.7749
        - name: longitude
          in: query
          required: true
          description: Longitude of the user's location
          schema:
            type: number
            format: float
            example: -122.4194
        - name: radius
          in: query
          required: false
          description: Radius in meters
          schema:
            type: integer
            format: int32
            example: 1000
        - name: limit
          in: query
          required: false
          description: The maximum number of results to return (default 10)
          schema:
            type: integer
            format: int32
            example: 20
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components/schemas/PaginatedLocationsWithRestaurantOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
  /locations/{locationId}/tables:
    post:
      tags:
        - Location
      summary: Create a table at a location
      description: Adds a new table with the given number of seats to the specified location.
      operationId: createTable
      parameters:
        - name: locationId
          in: path
          description: ID of the location where the table will be created
          required: true
          schema:
            type: integer
      requestBody:
        description: Optional additional data for the new table
        required: false
        content:
          application/json:
            schema:
              $ref: './components/schemas/TableInput.yaml'
      responses:
        '201':
          description: Table created successfully
          content:
            application/json:
              schema:
                $ref: './components/schemas/TableOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /locations/{locationId}/reservations:
    post:
      summary: Create a reservation for a table at the specified location
      tags:
        - Reservation
      parameters:
        - in: path
          name: locationId
          required: true
          description: ID of the location
          schema:
            type: string
            format: uuid
        - in: header
          name: Authorization
          description: JWT token for authorization
          required: true
          schema:
            type: string
      requestBody:
        description: Request body for creating a reservation
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/ReservationInput.yaml'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: './components/schemas/ReservationOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /tables/{tableId}:
    put:
      summary: Update a table
      tags:
        - Table
      parameters:
        - in: path
          name: tableId
          required: true
          description: ID of the table to update
          schema:
            type: integer
      requestBody:
        description: New details for the table
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/TableInput.yaml'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components/schemas/TableOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /reservations/{reservationId}:
    get:
      summary: Get a reservation by ID
      tags:
        - Reservation
      parameters:
        - name: reservationId
          in: path
          description: ID of the reservation to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './components/schemas/ReservationOutput.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    put:
      summary: Update a reservation by ID
      tags:
        - Reservation
      parameters:
        - in: path
          name: reservationId
          schema:
            type: integer
          required: true
          description: ID of the reservation to update
      requestBody:
        description: The reservation object to update
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/ReservationInput.yaml'
      responses:
        '200':
          description: Successfully updated the reservation
          content:
            application/json:
              schema:
                $ref: './components/schemas/ReservationOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
    delete:
      summary: Delete a reservation
      tags:
        - Reservation
      parameters:
        - in: path
          name: reservationId
          description: ID of the reservation to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Reservation deleted successfully
        '404':
          $ref: './components/responses/NotFound.yaml'
  /tables/{locationId}:
    get:
      tags:
        - Table
      summary: Get all tables by locationId
      parameters:
        - in: path
          name: locationId
          required: true
          description: The ID of the location to get tables for
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/TableOutput.yaml'
        '400':
          $ref: './components/responses/BadRequest.yaml'
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
  /photos/{photoId}:
    delete:
      summary: Delete a photo by ID
      tags:
        - Photo
      parameters:
        - in: path
          name: photoId
          required: true
          description: Id of the photo to delete
          schema:
            type: integer
      responses:
        '204':
          description: Successfully deleted the photo
        '401':
          $ref: './components/responses/Unauthorized.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
