server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs/
  swagger-ui:
    path: /swagger-ui.html

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/reserveat
    username: reserveat
    password: reserveat
